### ISSUE TITLE
Compilaition error with entities 0.14.0-preview.19

### ISSUE THREAD

**Issue by WaynGames** [lieene/UnityECS-CompoentStateTrack#2]
These lines don"t compile with entiteis 0.14.0-preview.19 and unity 2020.1.0f1

https://github.com/lieene/UnityECS-CompoentStateTrack/blob/dbaa6bf508762b459b0bd471e105787f1ebc11a1/ComponentExist.cs#L174-L175

I replaced them with 

```c#
var componentTypes = chunk.Archetype.GetComponentTypes();
var chunkTypeIds = (int*)componentTypes.GetUnsafePtr();
var chunkTypeCount = componentTypes.Length;
```

Seems to do the trick.

**Comment by lieene** [comment]
They are internal, let my make project with AsmReference

**Comment by lieene** [comment]
project set up.
