### ISSUE TITLE
Add package.json to handle dependancies

### ISSUE THREAD

**Issue by WaynGames** [lieene/UnityECS-CompoentStateTrack#3]
Some of your code relies on the new input system that is not preinstalled in unity.
You should prbably add a package.json to your repository to handle this dependancy or replace it with the legacy input system.
Making a package.json file will also simplify the import of your code into a unity project.

Also it relies on Entities and you should probably state somewhere what version of that package you use.

**Comment by lieene** [comment]
Sure.

**Comment by lieene** [comment]
done
